# Generated by Django 3.0.5 on 2020-12-24 17:31

import catalogapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=catalogapp.models.get_image_name, verbose_name='Изображение 200х200')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование для магазина')),
                ('art', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Url')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Распродажа')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Спецпредложение')),
                ('is_service', models.BooleanField(default=False, verbose_name='Услуга')),
                ('is_show', models.BooleanField(default=False, verbose_name='Виден для пользователей')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('quant', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('width', models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Ширина, см')),
                ('height', models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Высота, см')),
                ('depth', models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Глубина, см')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Вес, кг')),
                ('volume', models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Объем, м3')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogapp.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=catalogapp.models.get_image_name, verbose_name='Изображение 500x500')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.Good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
