# Generated by Django 3.1.4 on 2020-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_category_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Скидка, %'),
        ),
        migrations.AddField(
            model_name='good',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Старая цена'),
        ),
    ]
