# Generated by Django 3.0.5 on 2020-12-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0004_auto_20201225_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='quant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Количество'),
        ),
    ]
