# Generated by Django 3.1.4 on 2020-12-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0006_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Доступен в меню'),
        ),
    ]
