# Generated by Django 3.1.4 on 2020-12-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0007_auto_20201226_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='additive1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good_additive1', to='catalogapp.good', verbose_name='Добавка 1'),
        ),
        migrations.AddField(
            model_name='good',
            name='additive2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good_additive2', to='catalogapp.good', verbose_name='Добавка 2'),
        ),
        migrations.AddField(
            model_name='good',
            name='additive3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good_additive3', to='catalogapp.good', verbose_name='Добавка 3'),
        ),
        migrations.AddField(
            model_name='good',
            name='additive4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good_additive4', to='catalogapp.good', verbose_name='Добавка 4'),
        ),
        migrations.AddField(
            model_name='good',
            name='additive5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good_additive5', to='catalogapp.good', verbose_name='Добавка 5'),
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
