# Generated by Django 3.1.4 on 2020-12-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0008_auto_20201226_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=1600, verbose_name='Url')),
                ('quant1', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Количество 1')),
                ('quant2', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Количество 2')),
                ('quant3', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Количество 3')),
                ('quant4', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Количество 4')),
                ('quant5', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Количество 5')),
                ('additive1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_additive1', to='catalogapp.good', verbose_name='Добавка 1')),
                ('additive2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_additive2', to='catalogapp.good', verbose_name='Добавка 2')),
                ('additive3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_additive3', to='catalogapp.good', verbose_name='Добавка 3')),
                ('additive4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_additive4', to='catalogapp.good', verbose_name='Добавка 4')),
                ('additive5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_additive5', to='catalogapp.good', verbose_name='Добавка 5')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_good', to='catalogapp.good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
