# Generated by Django 3.1.4 on 2020-12-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0009_offer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('good', 'additive1', 'additive2', 'additive3', 'additive4', 'additive5', 'quant1', 'quant2', 'quant3', 'quant4', 'quant5')},
        ),
    ]
