# Generated by Django 3.0.5 on 2020-12-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0011_auto_20201226_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quant1',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Количество 1'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quant2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Количество 2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quant3',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Количество 3'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quant4',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Количество 4'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quant5',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Количество 5'),
        ),
    ]
