# Generated by Django 3.1.4 on 2020-12-30 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0013_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogapp.menuitem', verbose_name='Меню'),
        ),
    ]
