# Generated by Django 3.0.5 on 2020-12-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quant',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15, verbose_name='Количество'),
        ),
    ]
