# Generated by Django 3.1.4 on 2020-12-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0011_auto_20201226_1030'),
        ('cartapp', '0002_auto_20201225_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='good',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogapp.offer', verbose_name='Предложение'),
        ),
    ]
