# Generated by Django 3.1.4 on 2020-12-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=25, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, verbose_name='Объем, м3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, verbose_name='Вес, кг'),
        ),
    ]
